//
//  BugSnapAction.swift
//  BugSnap
//
//  Created by Héctor García Peña on 6/11/19.
//  Copyright © 2019 Grio. All rights reserved.
//

import Foundation

/**
    Protocol to define the action to perform when a BugSnap is triggered.
    The purpose of this protocol is to define a common interface of actions to be performed when a gesture for a bug snap is generated by the user.
*/
protocol BugSnapAction {
    
    /// Whether the action triggered requires a snapshot when the gesture is done
    var requiresSnapshot : Bool { get }
    
    /// Whether the action should be called in the main thread
    var executeInMainThread : Bool { get }
    
    /**
        The action to perform
        - Parameter snapshot: The image captured from the main window if required by the action.
    */
    func perform( snapshot : UIImage? )
    
}
