# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test Library"
  lane :test do
    run_tests(
      scheme: "BugSnap",
      clean: true
    )
  end

  private_lane :setup_keychain do
    if is_ci?
      # Create a temporary keychain to store the certificates.
      create_keychain(
        name: ENV["MATCH_KEYCHAIN_NAME"],
        password: ENV["MATCH_KEYCHAIN_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        add_to_search_list: true
      )
    end
  end

  private_lane :destroy_keychain do
    if is_ci?
      delete_keychain(name: ENV["MATCH_KEYCHAIN_NAME"])
    end
  end

  private_lane :set_match do |options|
    type = (options[:appstore] ? "appstore" : "development")
    if is_ci?
      match(
        type: type,
        readonly: true,
        keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
        keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"]
      )
    else
      match(type: type)
    end
  end

  desc "Build Dev ipa"
  lane :development do
    setup_keychain
    set_match(appstore: false)

    build_app(
      scheme: "BugSnap Demo App",
      output_directory: "output",
      output_name: "Bugsnap.ipa",
      configuration: "Debug",
      export_method: "development"
    )

    destroy_keychain
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_keychain
    set_match(appstore: true)

    build_app(
      scheme: "BugSnap Demo App",
      output_directory: "output",
      output_name: "Bugsnap.ipa",
      configuration: "Release",
      export_method: "app-store"
    )
    backup_xcarchive(
      destination: "output",
      zip: true
    )

    upload_to_testflight
    destroy_keychain
  end

  desc "Push a new release build to AppStore"
  lane :release do
    setup_keychain
    set_match(appstore: true)

    build_app(
      scheme: "BugSnap Demo App",
      output_directory: "output",
      output_name: "Bugsnap.ipa",
      configuration: "Release",
      export_method: "app-store"
    )
    backup_xcarchive(
      destination: "output",
      zip: true
    )

    upload_to_app_store       # Upload the screenshots and the binary to iTunes
    slack                     # Let your team-mates know the new version is live
    destroy_keychain
  end

  desc "Bump the build number"
  lane :bumpbuild do
    version = get_version_number(xcodeproj: "BugSnap Demo App/BugSnap Demo App.xcodeproj")
    build = increment_build_number(xcodeproj: "BugSnap Demo App/BugSnap Demo App.xcodeproj")
    puts "Bumped project to v#{version} (#{build}). Please remember to commit changes to git."
  end

  desc "Increment major version number (i.e.: X.0.0) + build bump"
  lane :bumpversionmajor do
    version = increment_version_number(
      xcodeproj: "BugSnap Demo App/BugSnap Demo App.xcodeproj",
      bump_type: "major"
    )
    build = increment_build_number(xcodeproj: "BugSnap Demo App/BugSnap Demo App.xcodeproj")
    puts "Bumped project to v#{version} (#{build}). Please remember to commit changes to git."
  end

  desc "Increment minor version number (i.e.: 1.X.0) + build bump"
  lane :bumpversionminor do
    version = increment_version_number(
      xcodeproj: "BugSnap Demo App/BugSnap Demo App.xcodeproj",
      bump_type: "minor"
    )
    build = increment_build_number(xcodeproj: "BugSnap Demo App/BugSnap Demo App.xcodeproj")
    puts "Bumped project to v#{version} (#{build}). Please remember to commit changes to git."
  end

  desc "Increment patch version number (i.e.: 1.1.X) + build bump"
  lane :bumpversionpatch do
    version = increment_version_number(
      xcodeproj: "BugSnap Demo App/BugSnap Demo App.xcodeproj",
      bump_type: "patch"
    )
    build = increment_build_number(xcodeproj: "BugSnap Demo App/BugSnap Demo App.xcodeproj")
    puts "Bumped project to v#{version} (#{build}). Please remember to commit changes to git."
  end
end
